"""Initial schema

Revision ID: 49f7ddf9c13c
Revises: 
Create Date: 2026-06-15 11:42:03.856053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f7ddf9c13c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique display name — 3 to 50 characters.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique e-mail address used for login and notifications.'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Password hash (Argon2 / bcrypt).'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-disable flag — inactive users cannot authenticate.'),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='Admin privilege flag.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated by the application.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the last row update.'),
    sa.CheckConstraint('char_length(email) >= 5', name='ck_users_email_min_length'),
    sa.CheckConstraint('char_length(username) >= 3', name='ck_users_username_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id — owner of this chat session.'),
    sa.Column('title', sa.String(length=200), server_default='New Chat', nullable=False, comment='Display title for this chat session.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated by the application.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the last row update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK → users.id — owner of this document.'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Original file name as uploaded by the user.'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='File size in bytes.'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type, e.g. application/pdf.'),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the upload.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated by the application.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the last row update.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='FK → chat_sessions.id — parent session.'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="Message role: 'user', 'assistant', or 'system'."),
    sa.Column('content', sa.Text(), nullable=False, comment='Full message body.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of message creation.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated by the application.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of row creation.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of the last row update.'),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role_valid'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index('ix_messages_session_id_timestamp', 'messages', ['session_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_id_timestamp', table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
