"""
backend/app/database/base.py
=============================
SQLAlchemy declarative base and shared column mixins.

Design Decisions:
-----------------
- A single `Base` class (from `DeclarativeBase`) is the ancestor of ALL ORM
  models. This lets SQLAlchemy track every mapped class in one registry, which
  Alembic uses to auto-generate migrations.
- `TimestampMixin` adds `created_at` / `updated_at` columns to any model that
  needs audit timestamps. Using a mixin (rather than putting these on Base
  directly) follows the Interface Segregation Principle — not every table needs
  timestamps, and those that don't shouldn't be forced to carry them.
- `server_default` / `onupdate` are handled at the database level, not the
  application level, so they work correctly even when rows are inserted/updated
  via raw SQL (e.g., migrations or external tools).
- `UUIDMixin` provides a UUID primary key — preferred over serial integers for
  distributed systems because IDs can be generated without a database round-trip.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedColumn, mapped_column


class Base(DeclarativeBase):
    """
    Shared declarative base for all SQLAlchemy ORM models.

    All models **must** inherit from this class (directly or via a mixin chain)
    so Alembic can discover them when generating migrations.

    Example
    -------
        class User(Base):
            __tablename__ = "users"
            ...
    """
    pass


class UUIDMixin:
    """
    Adds a UUID primary key column named `id`.

    The UUID is generated by the application layer (not the database) so the
    ID is known before the INSERT is executed — useful for creating related
    objects in the same transaction.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
        comment="Primary key — UUID v4 generated by the application.",
    )


class TimestampMixin:
    """
    Adds `created_at` and `updated_at` audit timestamp columns.

    - `created_at` is set once at INSERT time via the PostgreSQL `now()` function.
    - `updated_at` is refreshed on every UPDATE via the `onupdate` hook.
    Both columns are stored as timezone-aware UTC timestamps.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="UTC timestamp of row creation.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="UTC timestamp of the last row update.",
    )
